import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const beasiswaData = [
  // ========================================
  // 5.2 Beasiswa Dalam Negeri (SMA → S1)
  // ========================================
  {
    nama: "KIP Kuliah",
    provider: "Kemendikbud",
    negara: "Indonesia",
    jenjang: ["S1"],
    targetUser: ["SMA"],
    deadlineNote: "Periode pendaftaran biasanya Februari–April setiap tahun",
    cakupan: ["Biaya kuliah penuh", "Biaya hidup bulanan"],
    nilaiMinimum: 7.5,
    bidangStudi: ["Semua bidang"],
    bahasa: ["Indonesia"],
    persyaratan: {
      umum: ["Lulusan SMA/SMK/MA tahun berjalan atau maksimal 2 tahun sebelumnya", "Berasal dari keluarga kurang mampu", "Memiliki potensi akademik baik"],
      dokumen: ["KTP", "KK", "Ijazah/SKL", "Rapor", "Bukti tidak mampu (KIP/PKH/SKTM)"],
    },
    checklistDok: ["KTP", "KK", "Ijazah/SKL", "Rapor SMA", "Surat keterangan tidak mampu", "Pas foto"],
    urlResmi: "https://kip-kuliah.kemdikbud.go.id",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Beasiswa Unggulan Kemendikbud",
    provider: "Kemendikbud",
    negara: "Indonesia",
    jenjang: ["S1"],
    targetUser: ["SMA"],
    deadlineNote: "Pendaftaran biasanya Juli–Agustus setiap tahun",
    cakupan: ["Biaya kuliah", "Biaya hidup", "Biaya buku"],
    nilaiMinimum: 8.0,
    bidangStudi: ["Semua bidang prioritas nasional"],
    bahasa: ["Indonesia"],
    persyaratan: {
      umum: ["WNI", "Diterima di PTN/PTS terakreditasi A", "Prestasi akademik/non-akademik tingkat nasional/internasional"],
      dokumen: ["KTP", "Ijazah", "Transkrip/Rapor", "Sertifikat prestasi", "Essay rencana studi"],
    },
    checklistDok: ["KTP", "Ijazah/SKL", "Rapor", "Sertifikat prestasi", "Essay", "Surat rekomendasi", "Pas foto"],
    urlResmi: "https://beasiswaunggulan.kemdikbud.go.id",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Djarum Beasiswa Plus",
    provider: "Djarum Foundation",
    negara: "Indonesia",
    jenjang: ["S1"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Pendaftaran biasanya April–Mei setiap tahun untuk mahasiswa semester 4",
    cakupan: ["Tunjangan beasiswa", "Pelatihan soft skills", "Character building"],
    nilaiMinimum: 3.0,
    bidangStudi: ["Semua bidang"],
    bahasa: ["Indonesia"],
    persyaratan: {
      umum: ["Mahasiswa S1 semester 4 dari PTN/PTS", "IPK minimal 3.00", "Aktif organisasi", "Tidak menerima beasiswa lain"],
      dokumen: ["Transkrip nilai", "Surat rekomendasi", "Essay", "Sertifikat aktivitas"],
    },
    checklistDok: ["Transkrip", "Surat rekomendasi", "Essay", "Sertifikat organisasi", "Pas foto"],
    urlResmi: "https://djarumbeasiswaplus.org",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Beasiswa Sobat Bumi Pertamina",
    provider: "Pertamina Foundation",
    negara: "Indonesia",
    jenjang: ["S1"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Pendaftaran biasanya Maret–April setiap tahun",
    cakupan: ["Bantuan biaya pendidikan", "Pengembangan diri lingkungan"],
    nilaiMinimum: 3.0,
    bidangStudi: ["Lingkungan", "Energi", "Sains", "Teknik"],
    bahasa: ["Indonesia"],
    persyaratan: {
      umum: ["Mahasiswa aktif S1 di PTN mitra", "IPK minimal 3.00", "Berkomitmen pada isu lingkungan"],
      dokumen: ["Transkrip nilai", "Essay tentang lingkungan", "Surat rekomendasi"],
    },
    checklistDok: ["Transkrip", "Essay lingkungan", "Surat rekomendasi", "KTM", "KTP"],
    urlResmi: "https://pertaminafoundation.org/sobatbumi",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Beasiswa Bank Indonesia (S1)",
    provider: "Bank Indonesia",
    negara: "Indonesia",
    jenjang: ["S1"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Pendaftaran biasanya Februari–Maret setiap tahun",
    cakupan: ["Bantuan biaya pendidikan", "Pembinaan GenBI"],
    nilaiMinimum: 3.0,
    bidangStudi: ["Ekonomi", "Bisnis", "Hukum", "Sains", "Teknik"],
    bahasa: ["Indonesia"],
    persyaratan: {
      umum: ["Mahasiswa aktif S1 semester 3-7 di PTN mitra", "IPK minimal 3.00", "Tidak menerima beasiswa lain"],
      dokumen: ["Transkrip nilai", "KTM", "Surat keterangan tidak menerima beasiswa lain"],
    },
    checklistDok: ["Transkrip", "KTM", "Surat keterangan tidak menerima beasiswa lain", "Essay"],
    urlResmi: "https://www.bi.go.id/id/bi-institute/beasiswa-bi",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Tanoto Foundation TELADAN",
    provider: "Tanoto Foundation",
    negara: "Indonesia",
    jenjang: ["S1"],
    targetUser: ["SMA", "MAHASISWA"],
    deadlineNote: "Pendaftaran biasanya November–Januari setiap tahun",
    cakupan: ["Biaya kuliah penuh", "Tunjangan bulanan", "Pelatihan kepemimpinan", "Magang"],
    nilaiMinimum: 8.5,
    bidangStudi: ["Semua bidang"],
    bahasa: ["Indonesia", "Inggris"],
    persyaratan: {
      umum: ["Calon mahasiswa baru atau mahasiswa semester 1 di 9 PTN mitra", "Prestasi akademik tinggi", "Jiwa kepemimpinan"],
      dokumen: ["Rapor", "Sertifikat prestasi", "Essay kepemimpinan"],
    },
    checklistDok: ["Rapor", "Sertifikat prestasi", "Essay kepemimpinan", "Surat rekomendasi", "KTP"],
    urlResmi: "https://www.tanotofoundation.org/teladan",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Beasiswa Sampoerna Foundation",
    provider: "Sampoerna Foundation",
    negara: "Indonesia",
    jenjang: ["S1"],
    targetUser: ["SMA"],
    deadlineNote: "Periode pendaftaran berbeda untuk Sampoerna Academy/University",
    cakupan: ["Biaya kuliah penuh atau partial", "Biaya hidup"],
    nilaiMinimum: 8.0,
    bidangStudi: ["Bisnis", "Sains", "Teknik", "Pendidikan"],
    bahasa: ["Inggris"],
    persyaratan: {
      umum: ["Lulusan SMA dengan nilai unggul", "Kemampuan bahasa Inggris baik", "Berkomitmen pada pengembangan masyarakat"],
      dokumen: ["Rapor", "Sertifikat TOEFL/IELTS", "Essay", "Surat rekomendasi"],
    },
    checklistDok: ["Rapor", "Sertifikat bahasa Inggris", "Essay", "Surat rekomendasi", "KTP"],
    urlResmi: "https://www.sampoernafoundation.org",
    sourceType: "MANUAL",
    verified: true,
  },

  // ========================================
  // 5.3 Beasiswa Dalam Negeri (S2/S3)
  // ========================================
  {
    nama: "LPDP Reguler",
    provider: "LPDP Kemenkeu",
    negara: "Indonesia",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Dibuka 2x setahun: Tahap 1 (Januari–Februari) dan Tahap 2 (Juni–Juli)",
    cakupan: ["Biaya kuliah penuh", "Biaya hidup bulanan", "Biaya kedatangan", "Asuransi", "Tunjangan keluarga"],
    ipkMinimum: 3.0,
    toeflMinimum: 500,
    ieltsMinimum: 6.0,
    bidangStudi: ["Semua bidang prioritas LPDP"],
    bahasa: ["Indonesia", "Inggris"],
    rubrikEssay: {
      kontribusi: "Rencana kontribusi setelah lulus untuk Indonesia (30%)",
      rencana: "Rencana studi yang spesifik dan terukur (30%)",
      kepemimpinan: "Pengalaman kepemimpinan dan dampak (20%)",
      kepribadian: "Karakter dan nilai personal (20%)",
    },
    persyaratan: {
      umum: ["WNI", "Lulusan S1/S2 dari PT terakreditasi", "IPK minimal 3.00 (S1) atau 3.25 (S2)", "Skor TOEFL/IELTS sesuai kategori", "Belum berusia 35 tahun (S2) atau 40 tahun (S3)"],
      dokumen: ["Ijazah", "Transkrip", "Sertifikat bahasa", "LoA (jika ada)", "Surat rekomendasi", "Essay kontribusi"],
    },
    checklistDok: ["KTP", "Ijazah", "Transkrip", "Sertifikat TOEFL/IELTS", "LoA Unconditional", "Surat rekomendasi (2)", "Essay kontribusi", "Rencana studi", "Surat pernyataan", "Pas foto"],
    urlResmi: "https://lpdp.kemenkeu.go.id",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "LPDP Afirmasi",
    provider: "LPDP Kemenkeu",
    negara: "Indonesia",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Dibuka 2x setahun bersamaan dengan LPDP Reguler",
    cakupan: ["Biaya kuliah penuh", "Biaya hidup bulanan", "Biaya kedatangan", "Asuransi", "Tunjangan keluarga"],
    ipkMinimum: 2.5,
    toeflMinimum: 450,
    ieltsMinimum: 5.5,
    bidangStudi: ["Semua bidang prioritas LPDP"],
    bahasa: ["Indonesia", "Inggris"],
    persyaratan: {
      umum: ["WNI dari kelompok afirmasi (daerah 3T, prasejahtera, disabilitas, alumni Bidikmisi/KIP)", "IPK minimal 2.50", "Skor bahasa lebih rendah dari LPDP Reguler"],
      dokumen: ["KTP", "Ijazah", "Transkrip", "Bukti afirmasi (kartu, surat keterangan)", "Surat rekomendasi", "Essay"],
    },
    checklistDok: ["KTP", "Ijazah", "Transkrip", "Bukti kelompok afirmasi", "Sertifikat bahasa", "Surat rekomendasi", "Essay", "Rencana studi"],
    urlResmi: "https://lpdp.kemenkeu.go.id",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Beasiswa Unggulan Kemendikbud (S2/S3)",
    provider: "Kemendikbud",
    negara: "Indonesia",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Pendaftaran biasanya Juli–Agustus setiap tahun",
    cakupan: ["Biaya kuliah", "Biaya hidup", "Biaya buku", "Biaya penelitian"],
    ipkMinimum: 3.25,
    bidangStudi: ["Sesuai prioritas nasional"],
    bahasa: ["Indonesia", "Inggris"],
    persyaratan: {
      umum: ["WNI", "Diterima di PT terakreditasi A/B+", "Prestasi tingkat nasional/internasional"],
      dokumen: ["Ijazah", "Transkrip", "LoA", "Sertifikat prestasi", "Essay rencana studi"],
    },
    checklistDok: ["KTP", "Ijazah", "Transkrip", "LoA", "Sertifikat prestasi", "Essay", "Surat rekomendasi"],
    urlResmi: "https://beasiswaunggulan.kemdikbud.go.id",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Beasiswa Pendidikan Indonesia (BPI)",
    provider: "Kemendikbud",
    negara: "Indonesia",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Pendaftaran biasanya April–Mei setiap tahun",
    cakupan: ["Biaya kuliah penuh", "Biaya hidup", "Tunjangan buku", "Biaya kedatangan"],
    ipkMinimum: 3.0,
    toeflMinimum: 500,
    ieltsMinimum: 6.0,
    bidangStudi: ["Pendidikan", "Riset prioritas Kemendikbud"],
    bahasa: ["Indonesia", "Inggris"],
    persyaratan: {
      umum: ["Dosen, tenaga kependidikan, pelaku budaya, atau calon dosen", "IPK minimal 3.00", "Skor bahasa sesuai jenjang"],
      dokumen: ["Ijazah", "Transkrip", "Sertifikat bahasa", "LoA", "Surat tugas/keterangan instansi"],
    },
    checklistDok: ["KTP", "Ijazah", "Transkrip", "LoA", "Sertifikat TOEFL/IELTS", "Surat rekomendasi", "Essay rencana studi"],
    urlResmi: "https://beasiswa.kemdikbud.go.id",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Beasiswa Bank Indonesia (S2)",
    provider: "Bank Indonesia",
    negara: "Indonesia",
    jenjang: ["S2"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Pendaftaran biasanya Februari–Maret setiap tahun",
    cakupan: ["Bantuan biaya kuliah", "Tunjangan bulanan"],
    ipkMinimum: 3.25,
    bidangStudi: ["Ekonomi", "Keuangan", "Hukum", "Statistik"],
    bahasa: ["Indonesia"],
    persyaratan: {
      umum: ["Mahasiswa S2 aktif di PTN mitra", "IPK S1 minimal 3.25", "Tidak menerima beasiswa lain"],
      dokumen: ["Ijazah S1", "Transkrip", "KTM", "Surat keterangan tidak menerima beasiswa lain"],
    },
    checklistDok: ["Ijazah S1", "Transkrip", "KTM", "Surat keterangan tidak menerima beasiswa lain", "Essay"],
    urlResmi: "https://www.bi.go.id/id/bi-institute/beasiswa-bi",
    sourceType: "MANUAL",
    verified: true,
  },

  // ========================================
  // 5.4 Beasiswa Luar Negeri (SMA → S1)
  // ========================================
  {
    nama: "NTU ASEAN Undergraduate Scholarship",
    provider: "Nanyang Technological University",
    negara: "Singapura",
    jenjang: ["S1"],
    targetUser: ["SMA"],
    deadlineNote: "Deadline biasanya Februari–Maret setiap tahun untuk intake Agustus",
    cakupan: ["Biaya kuliah penuh", "Tunjangan hidup tahunan SGD 5,800", "Akomodasi tahun pertama", "Tiket pesawat"],
    nilaiMinimum: 8.5,
    toeflMinimum: 600,
    ieltsMinimum: 6.5,
    bidangStudi: ["Engineering", "Sains", "Bisnis", "Humaniora"],
    bahasa: ["Inggris"],
    persyaratan: {
      umum: ["WN ASEAN (selain Singapura)", "Prestasi akademik unggul", "Aktif kepemimpinan", "Lulus seleksi NTU"],
      dokumen: ["Rapor", "Sertifikat IELTS/TOEFL/SAT", "Essay", "Surat rekomendasi"],
    },
    checklistDok: ["Rapor", "Sertifikat bahasa", "SAT (jika diminta)", "Essay", "Surat rekomendasi", "Paspor"],
    urlResmi: "https://www.ntu.edu.sg/admissions/undergraduate/scholarships",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "NUS Undergraduate Scholarship",
    provider: "National University of Singapore",
    negara: "Singapura",
    jenjang: ["S1"],
    targetUser: ["SMA"],
    deadlineNote: "Deadline biasanya Maret setiap tahun untuk intake Agustus",
    cakupan: ["Biaya kuliah penuh", "Tunjangan hidup tahunan", "Akomodasi tahun pertama"],
    nilaiMinimum: 8.5,
    toeflMinimum: 600,
    ieltsMinimum: 6.5,
    bidangStudi: ["Engineering", "Computing", "Sains", "Bisnis", "Humaniora"],
    bahasa: ["Inggris"],
    persyaratan: {
      umum: ["WN ASEAN (selain Singapura)", "Diterima di NUS", "Prestasi akademik unggul"],
      dokumen: ["Rapor", "Sertifikat bahasa", "Essay", "Surat rekomendasi"],
    },
    checklistDok: ["Rapor", "Sertifikat bahasa", "SAT (jika diminta)", "Essay", "Surat rekomendasi", "Paspor"],
    urlResmi: "https://www.nus.edu.sg/oam/scholarships",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "KAIST International Scholarship (S1)",
    provider: "Korea Advanced Institute of Science and Technology",
    negara: "Korea Selatan",
    jenjang: ["S1"],
    targetUser: ["SMA"],
    deadlineNote: "Deadline biasanya September–Oktober untuk intake musim semi tahun berikutnya",
    cakupan: ["Biaya kuliah penuh", "Tunjangan hidup bulanan KRW 350,000", "Asuransi"],
    nilaiMinimum: 8.5,
    toeflMinimum: 83,
    ieltsMinimum: 6.5,
    bidangStudi: ["Sains", "Engineering", "Teknologi"],
    bahasa: ["Inggris"],
    persyaratan: {
      umum: ["WNA (bukan WN Korea)", "Lulusan SMA atau setara", "Kemampuan bahasa Inggris baik"],
      dokumen: ["Rapor", "Sertifikat TOEFL/IELTS", "Essay", "Surat rekomendasi (2)"],
    },
    checklistDok: ["Rapor", "Sertifikat bahasa", "Essay", "Surat rekomendasi", "Paspor", "Pas foto"],
    urlResmi: "https://admission.kaist.ac.kr/intl-undergraduate",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Stipendium Hungaricum",
    provider: "Pemerintah Hungaria",
    negara: "Hungaria",
    jenjang: ["S1", "S2", "S3"],
    targetUser: ["SMA", "MAHASISWA"],
    deadlineNote: "Deadline biasanya Januari setiap tahun untuk intake September",
    cakupan: ["Biaya kuliah penuh", "Tunjangan bulanan HUF 43,700 (S1) / HUF 140,000 (S3)", "Akomodasi gratis atau subsidi", "Asuransi kesehatan"],
    nilaiMinimum: 7.5,
    ipkMinimum: 3.0,
    toeflMinimum: 500,
    ieltsMinimum: 5.5,
    bidangStudi: ["Engineering", "Sains", "Bisnis", "Humaniora", "Kedokteran"],
    bahasa: ["Inggris", "Hungaria"],
    persyaratan: {
      umum: ["WN dari negara mitra (termasuk Indonesia)", "Memenuhi syarat akademik dan bahasa", "Diterima di universitas Hungaria"],
      dokumen: ["Ijazah/SKL", "Transkrip/Rapor", "Sertifikat bahasa", "Motivation letter", "Medical certificate"],
    },
    checklistDok: ["Ijazah", "Transkrip", "Sertifikat bahasa", "Motivation letter", "Medical certificate", "Paspor", "Surat rekomendasi"],
    urlResmi: "https://stipendiumhungaricum.hu",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "MEXT Undergraduate Scholarship",
    provider: "Pemerintah Jepang (MEXT)",
    negara: "Jepang",
    jenjang: ["S1"],
    targetUser: ["SMA"],
    deadlineNote: "Deadline biasanya Mei setiap tahun untuk keberangkatan April tahun berikutnya",
    cakupan: ["Biaya kuliah penuh", "Tunjangan bulanan JPY 117,000", "Tiket pesawat PP", "Bebas biaya ujian masuk"],
    nilaiMinimum: 8.4,
    bidangStudi: ["Sains", "Engineering", "Pertanian", "Humaniora", "Sosial"],
    bahasa: ["Jepang", "Inggris"],
    persyaratan: {
      umum: ["WNI lulusan SMA", "Usia maksimal 24 tahun", "Lahir setelah tanggal tertentu sesuai pengumuman tahunan", "Sehat jasmani rohani"],
      dokumen: ["Rapor", "Ijazah/SKL", "Sertifikat bahasa Jepang/Inggris", "Health certificate", "Essay"],
    },
    checklistDok: ["Rapor", "Ijazah/SKL", "Sertifikat bahasa", "Health certificate", "Essay rencana studi", "Paspor"],
    urlResmi: "https://www.id.emb-japan.go.jp/sch.html",
    sourceType: "MANUAL",
    verified: true,
  },

  // ========================================
  // 5.5 Beasiswa Luar Negeri (S2/S3)
  // ========================================
  {
    nama: "Chevening Scholarship",
    provider: "Pemerintah Inggris (FCDO)",
    negara: "Inggris",
    jenjang: ["S2"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Deadline biasanya September–November setiap tahun untuk keberangkatan tahun berikutnya",
    cakupan: ["Biaya kuliah penuh", "Tunjangan hidup bulanan", "Tiket pesawat PP", "Visa", "Tunjangan kedatangan"],
    ipkMinimum: 3.0,
    ieltsMinimum: 6.5,
    pengalamanMin: 2,
    bidangStudi: ["Semua bidang di universitas UK"],
    bahasa: ["Inggris"],
    rubrikEssay: {
      leadership: "Bukti pengalaman dan potensi kepemimpinan (25%)",
      networking: "Kemampuan membangun jaringan dan hubungan (25%)",
      studi: "Pilihan studi dan rencana yang jelas (25%)",
      karir: "Rencana karir setelah lulus (25%)",
    },
    persyaratan: {
      umum: ["WN dari negara Chevening (termasuk Indonesia)", "Pengalaman kerja minimal 2 tahun (2,800 jam)", "Diterima di 3 universitas UK", "Kembali ke negara asal minimal 2 tahun"],
      dokumen: ["Ijazah", "Transkrip", "Sertifikat IELTS", "4 Essay", "Surat rekomendasi (2)"],
    },
    checklistDok: ["Paspor", "Ijazah", "Transkrip", "Sertifikat IELTS", "4 Essay (Leadership, Networking, Studi, Karir)", "Surat rekomendasi (2)", "LoA dari 3 universitas UK"],
    urlResmi: "https://www.chevening.org",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Australia Awards Scholarship",
    provider: "Pemerintah Australia (DFAT)",
    negara: "Australia",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Deadline biasanya April setiap tahun untuk keberangkatan tahun berikutnya",
    cakupan: ["Biaya kuliah penuh", "Tunjangan hidup", "Tiket pesawat PP", "OSHC asuransi kesehatan", "Pelatihan pra-keberangkatan"],
    ipkMinimum: 2.9,
    ieltsMinimum: 6.5,
    bidangStudi: ["Bidang prioritas pembangunan: kesehatan, pendidikan, pertanian, ekonomi, governance"],
    bahasa: ["Inggris"],
    persyaratan: {
      umum: ["WNI", "IPK minimal 2.90 (publik) atau 3.00 (swasta)", "IELTS 6.5 / TOEFL iBT 84", "Tidak sedang mengambil beasiswa lain"],
      dokumen: ["Ijazah S1", "Transkrip", "IELTS", "CV", "Essay", "Surat rekomendasi"],
    },
    checklistDok: ["KTP", "Paspor", "Ijazah", "Transkrip", "Sertifikat IELTS", "CV", "Essay", "Surat rekomendasi", "Statement of Purpose"],
    urlResmi: "https://www.australiaawardsindonesia.org",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "DAAD Scholarship",
    provider: "Deutscher Akademischer Austauschdienst",
    negara: "Jerman",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Deadline berbeda per program, umumnya Agustus–Oktober setiap tahun",
    cakupan: ["Biaya kuliah", "Tunjangan bulanan EUR 934 (S2) / EUR 1,300 (S3)", "Asuransi kesehatan", "Tiket pesawat", "Tunjangan rumah"],
    ipkMinimum: 3.0,
    toeflMinimum: 550,
    ieltsMinimum: 6.0,
    pengalamanMin: 2,
    bidangStudi: ["Engineering", "Sains", "Sosial", "Ekonomi", "Pengembangan internasional"],
    bahasa: ["Inggris", "Jerman"],
    persyaratan: {
      umum: ["WN dari negara berkembang (termasuk Indonesia)", "Pengalaman kerja minimal 2 tahun di bidang relevan", "Lulus S1 dengan IPK baik"],
      dokumen: ["Ijazah", "Transkrip", "Sertifikat bahasa", "CV", "Motivation letter", "Surat rekomendasi (2)"],
    },
    checklistDok: ["Ijazah", "Transkrip", "Sertifikat IELTS/TOEFL atau bahasa Jerman", "CV", "Motivation letter", "Research proposal (S3)", "Surat rekomendasi (2)", "Paspor"],
    urlResmi: "https://www.daad.de/en",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Fulbright Scholarship",
    provider: "AMINEF / U.S. Department of State",
    negara: "Amerika Serikat",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Deadline biasanya Februari setiap tahun untuk keberangkatan tahun berikutnya",
    cakupan: ["Biaya kuliah penuh", "Tunjangan bulanan", "Tiket pesawat PP", "Asuransi kesehatan", "Tunjangan buku"],
    ipkMinimum: 3.0,
    toeflMinimum: 80,
    ieltsMinimum: 6.5,
    pengalamanMin: 2,
    bidangStudi: ["Semua bidang kecuali kedokteran klinis"],
    bahasa: ["Inggris"],
    persyaratan: {
      umum: ["WNI", "IPK minimal 3.00", "TOEFL iBT 80 atau IELTS 6.5", "Komitmen kembali ke Indonesia minimal 2 tahun"],
      dokumen: ["Ijazah", "Transkrip", "TOEFL iBT", "CV", "Essay", "Surat rekomendasi (3)"],
    },
    checklistDok: ["KTP", "Paspor", "Ijazah", "Transkrip", "Sertifikat TOEFL iBT", "CV", "Essay (Personal Statement, Study Objective)", "Surat rekomendasi (3)"],
    urlResmi: "https://www.aminef.or.id",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "MEXT Graduate Scholarship",
    provider: "Pemerintah Jepang (MEXT)",
    negara: "Jepang",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Deadline biasanya Mei setiap tahun untuk keberangkatan tahun berikutnya",
    cakupan: ["Biaya kuliah penuh", "Tunjangan bulanan JPY 144,000 (S2) / JPY 145,000-148,000 (S3)", "Tiket pesawat PP", "Bebas biaya ujian masuk"],
    ipkMinimum: 3.0,
    bidangStudi: ["Sains", "Engineering", "Sosial", "Humaniora", "Kedokteran"],
    bahasa: ["Jepang", "Inggris"],
    persyaratan: {
      umum: ["WNI", "Usia maksimal 35 tahun", "Lulus S1/S2 dengan IPK baik", "Sehat jasmani rohani"],
      dokumen: ["Ijazah", "Transkrip", "Research plan", "Sertifikat bahasa Jepang/Inggris", "Surat rekomendasi"],
    },
    checklistDok: ["Ijazah", "Transkrip", "Research plan", "Sertifikat bahasa", "Health certificate", "Surat rekomendasi", "Paspor"],
    urlResmi: "https://www.id.emb-japan.go.jp/sch.html",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "KAIST International Scholarship (S2/S3)",
    provider: "Korea Advanced Institute of Science and Technology",
    negara: "Korea Selatan",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Deadline biasanya April–Mei untuk intake musim gugur, September–Oktober untuk musim semi",
    cakupan: ["Biaya kuliah penuh", "Tunjangan hidup KRW 300,000-400,000/bulan", "Asuransi kesehatan"],
    ipkMinimum: 3.0,
    toeflMinimum: 83,
    ieltsMinimum: 6.5,
    bidangStudi: ["Sains", "Engineering", "Teknologi", "Bisnis"],
    bahasa: ["Inggris"],
    persyaratan: {
      umum: ["WNA (bukan WN Korea)", "Lulus S1/S2 dengan IPK minimal 3.00", "Skor bahasa Inggris memenuhi"],
      dokumen: ["Ijazah", "Transkrip", "Sertifikat TOEFL/IELTS", "Research proposal", "Surat rekomendasi (2)"],
    },
    checklistDok: ["Ijazah", "Transkrip", "Sertifikat bahasa", "Research proposal", "Surat rekomendasi", "Paspor", "CV"],
    urlResmi: "https://admission.kaist.ac.kr/intl-graduate",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "Erasmus Mundus Joint Master",
    provider: "European Commission",
    negara: "Eropa (Multi-negara)",
    jenjang: ["S2"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Deadline berbeda per program, umumnya November–Februari setiap tahun",
    cakupan: ["Biaya kuliah penuh", "Tunjangan bulanan EUR 1,400", "Tunjangan perjalanan", "Asuransi"],
    ipkMinimum: 3.0,
    toeflMinimum: 550,
    ieltsMinimum: 6.5,
    bidangStudi: ["Multidisiplin sesuai program EMJM"],
    bahasa: ["Inggris", "Bahasa Eropa lain"],
    persyaratan: {
      umum: ["Lulus S1", "Belajar di minimal 2 negara Eropa", "Kemampuan bahasa Inggris baik"],
      dokumen: ["Ijazah", "Transkrip", "Sertifikat bahasa", "Motivation letter", "CV", "Surat rekomendasi"],
    },
    checklistDok: ["Ijazah", "Transkrip", "Sertifikat IELTS/TOEFL", "Motivation letter", "CV", "Surat rekomendasi (2)", "Paspor"],
    urlResmi: "https://erasmus-plus.ec.europa.eu",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "VLIR-UOS Scholarship",
    provider: "Pemerintah Belgia (Flanders)",
    negara: "Belgia",
    jenjang: ["S2"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Deadline biasanya Februari–Maret setiap tahun untuk keberangkatan September",
    cakupan: ["Biaya kuliah penuh", "Tunjangan bulanan EUR 1,150", "Asuransi", "Tiket pesawat"],
    ipkMinimum: 3.0,
    toeflMinimum: 550,
    ieltsMinimum: 6.0,
    pengalamanMin: 2,
    bidangStudi: ["Pembangunan internasional", "Kesehatan global", "Pertanian", "Manajemen lingkungan"],
    bahasa: ["Inggris"],
    persyaratan: {
      umum: ["WN dari negara mitra (termasuk Indonesia)", "Pengalaman kerja minimal 2 tahun di bidang pembangunan", "Maksimal 35 tahun"],
      dokumen: ["Ijazah", "Transkrip", "Sertifikat bahasa", "Motivation letter", "CV", "Surat rekomendasi"],
    },
    checklistDok: ["Ijazah", "Transkrip", "Sertifikat IELTS/TOEFL", "Motivation letter", "CV", "Surat rekomendasi", "Paspor"],
    urlResmi: "https://www.vliruos.be/scholarships",
    sourceType: "MANUAL",
    verified: true,
  },
  {
    nama: "KNB Scholarship",
    provider: "Kemendikbud Indonesia",
    negara: "Indonesia",
    jenjang: ["S2", "S3"],
    targetUser: ["MAHASISWA"],
    deadlineNote: "Deadline biasanya Maret–April setiap tahun untuk intake September",
    cakupan: ["Biaya kuliah penuh", "Tunjangan hidup", "Tiket pesawat PP", "Tunjangan kedatangan", "Asuransi"],
    ipkMinimum: 3.0,
    toeflMinimum: 500,
    ieltsMinimum: 6.0,
    bidangStudi: ["Semua bidang di universitas mitra Indonesia"],
    bahasa: ["Indonesia", "Inggris"],
    persyaratan: {
      umum: ["WNA (bukan WNI)", "Maksimal 35 tahun (S2) atau 40 tahun (S3)", "Lulus S1/S2 dengan IPK baik"],
      dokumen: ["Ijazah", "Transkrip", "Sertifikat bahasa", "Motivation letter", "Research proposal"],
    },
    checklistDok: ["Ijazah", "Transkrip", "Sertifikat bahasa", "Motivation letter", "Research proposal (S3)", "Surat rekomendasi", "Paspor"],
    urlResmi: "https://knb.kemdikbud.go.id",
    sourceType: "MANUAL",
    verified: true,
  },
];

async function main() {
  console.log(`🌱 Seeding ${beasiswaData.length} beasiswa...`);

  // Clear existing seed data (only MANUAL ones, keep SCRAPED)
  await prisma.beasiswa.deleteMany({ where: { sourceType: "MANUAL" } });
  console.log("✓ Cleared existing manual seed data");

  for (const data of beasiswaData) {
    await prisma.beasiswa.create({
      data: {
        ...data,
        verifiedAt: data.verified ? new Date() : null,
      },
    });
    console.log(`  ✓ ${data.nama}`);
  }

  console.log(`\n✅ Successfully seeded ${beasiswaData.length} beasiswa`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
